apiVersion: v1
kind: Secret
metadata:
  name: {{ include "podinfo.SecretName" . }}
  labels:
    app: {{ template "podinfo.name" . }}
    chart: {{ template "podinfo.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
stringData:
    {{ toYaml .Values.encriptedSecretStringData | nindent 2 }}