---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: podinfo-prod
  namespace: prod
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: semver:~1.0
spec:
  releaseName: podinfo-prod
  chart:
    git: git@github.com:xtrasolver/helm-operator-get-started
    path: charts/podinfo
    ref: master
  values:
    image:
      repository: xtrasolver/podinfo
      tag: 1.0.3
    replicaCount: 5
    secrets:
      - secret1: prod-value1
      - secret2: prod-value2