---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: podinfo-prod
  namespace: prod
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: semver:~0.4
spec:
  releaseName: podinfo-prod
  chart:
    git: git@github.com:xtrasolver/helm-operator-get-started
    path: charts/podinfo
    ref: master
  values:
    image:
      repository: xtrasolver/podinfo
      tag: 1.0.0
    replicaCount: 3
